---
name: Spelling
on: [pull_request]

jobs:
  run:
    name: Spell Check with Typos
    runs-on: self-hosted
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v4

    - name: Check spelling of repo
      uses: crate-ci/typos@master

